---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---
```{r}
v1<-c(1:6)
v1
```
```{r}
m1<-matrix(c(1:6),2,3)
m1

class(m1) #類型
typeof(m1) #storage type

m1[[2]]
```
```{r}
m2<-matrix(c("a","b","c","d"),2,2)
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
ad<-m2[c(T,F,F,T)]
a
c
bd
ad
```
### data frame
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
class(StuDF)
typeof(StuDF)
length(StuDF)
class(StuDF$姓名)
typeof(StuDF$姓名)
length(StuDF$姓名)
```
```{r}
StuDF[[2]][[3]]
StuDF[3,2]
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3
class(StuDF3)
StuDF3
```
```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
dataframe:table
list
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m)
```
```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
matObj1[c(1,4),c(2,3)]
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
classSurvey[c(4,5)]
lindex<-classSurvey$性別=="女"
classSurvey[,c(lindex)]
```



