---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
b <- "hello"
```

```{r}
bvector <- c("hello","how r u?")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep='\n')
```

```{r}
l <- c(T,F,TRUE,FALSE)
class(l)
```
```{r}
sum(l)
```
```{r}
f <- factor(c('a','b','c'))
```
```{r}
f1 <- c('a','b','c')
class(f)
f
class(f1)
f1
f2 <- factor(c('a','a','c'))
f2
f3 <- c('a','b','c')
f3
#factor 有 level  (類別，以整數儲存)
```
```{r}
as.interger(f1)
```
```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace)
#as.xxx 把資料轉成xxx形式
#常用 字串 數字 轉換 eg.學號
```
```{r}
typeof(birthplace)
class(birthplace)
levels(birthplace)

```
```{r}
string <- c("1","3","-5")
class(string)
string
st2num <- as.integer(string)
class(st2num)
st2num
```
```{r}
library(lubridate)
dtobj <- ymd_hms('1970-01-01 00:02:53')
dtobj
dtobjv <- ymd_hms(c('1970-01-01 00:02:53','1997-01-22 00:04:45'))
dtobjv
class(dtobjv)
```
```{r}
typeof(dtobj)
as.numeric(dtobj)
```


