---
title: "0529"
author: "yianchiu"
date: "2019年5月29日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
textbookURL<-function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#section")
  textbookURL()
```

```{r}
demand_supply_fun<-function(P,a,b,c,d){
  Qs<-a+b*P
  Qd<-c-d*P
  return(
    list(Qs=Qs,Qd=Qd,超額供給量=Qs-Qd)
  )
}
```


```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  
if (!studentID %in% transcriptDataFinal$學號){
  message("查無此學號")
}
else{message(cat("顯示",GPA))}
}
```
Implement a fizzbuzz function. It takes a single number as input. If the number is divisible by three, it returns “fizz”. If it’s divisible by five it returns “buzz”. If it’s divisible by three and five, it returns “fizzbuzz”. Otherwise, it returns the number. Make sure you first write working code before you create the function. –From, R for Data Science.
```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}
```


