---
title: '2019-04-17'
author: "林茂廷"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
plasticContainer
#元素有命名以$表示
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```
```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

# 一個中括號只留在取多個元素時用
# 只取一個元素時用兩個中括號
```{r}
plasticContainer[["greenBox"]] [1]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單
成績單[[1]]
成績單[["個經"]]
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

name<-studentRecord[[2]]
thdgrade<-studentRecord[[4]][[3]]
name
thdgrade
```

```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
extract1 #保有母層list的架構(留有greenbox的資訊)
extract2 #無母層資訊(greenbox"內"的資訊)extract2即greenbox
typeof(extract1)
typeof(extract2)
length(extract1)
length(extract2)
```
# 用一個中括號取 會保有母層次的class結構
```{r}
length(plasticContainer)
typeof(plasticContainer[[1]])
typeof(plasticContainer[[c(1)]])
typeof(plasticContainer[c(1)])
typeof(plasticContainer[c(1,3)])
typeof(plasticContainer[c(T,F,T)])
```
取出paper
```{r}
extract1[[1]][[1]]
extract2[[1]]
# 不能使用[]的原因!
# []保有母層架構(仍為list)
# 取不出paper
# 只取一個元素用[[]]!!!
extract1[1][[1]]
```

6.4.3
```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```
```{r}
typeof(成績單)
typeof(plasticContainer)
```

6.4.4
```{r}
your_github_username <- "anny12809200"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
commitCheck
```

